##定义对象/Map集合
#user:
#  name: Tom
#  age: 20
#  address: beijing
##定义数组/set/List
#hobby:
#  - Java
#  - C
#  - Python

# mysql数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
#    password:

# mybatis配置
mybatis:
  configuration:
    #指定输出日志到控制台上
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#定义阿里云
aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:

server:
  port: 520